### ISSUE TITLE
关于Actions,直接使用原文会不会更好一些?

### ISSUE THREAD

**Issue by dive2Pro** [SangKa/MobX-Docs-CN#2]
类似
```
## Actions(动作)

任何应用都有动作。动作是任何用来修改状态的东西。

使用MobX你可以在代码中显示的标记出动作所在的位置。
```
换成这样会不会更好理解一些?
```
## Actions(动作)

任何应用都有Actions。Actions是任何用来修改状态的东西。

使用MobX你可以在代码中显示的标记出Actions所在的位置。
```

**Comment by dive2Pro** [comment]
以及一些类似的api,比如 `Computed` 这些会在使用中用到的关键字.

**Comment by SangKa** [comment]
确实可以直接使用原文，不做翻译。
对于像 Observable 这样的没有标准中文对应的词，建议直接使用原文。
但对于 Action 和 Observer 这种大家有普遍共识的单词可以直接翻译成中文，以避免有些这类词汇聚集的语句读起来像读原文。而且对于这类词汇一般都在标题处做了英汉对照 (例如 ## Actions(动作))。
补充: 目前整个文档都采用了此种方式。

**Comment by SangKa** [comment]
如果愿意持续参与文档维护，可以留个微信，我们建个微信群，这样方便后续关于文档意见的沟通。
