### ISSUE TITLE
同步 MobX 4 文档

### ISSUE THREAD

**Issue by SangKa** [SangKa/MobX-Docs-CN#40]

**Comment by chasewoo** [comment]
@SangKa  MobX 4 文档的同步工作到什么地步了？如何参与？

**Comment by SangKa** [comment]
@minowu  差不多明天就可以完成 改动点很多 但改动量不是太大

**Comment by chasewoo** [comment]
@SangKa 在哪条分支上？有机会可以加入今后的翻译组。

**Comment by SangKa** [comment]
目前只有 master 分支
4 更新的部分还在我本地 没有提交
有兴趣参与的话等同步完这次大更新之后 可以针对文档做次校对 提升下翻译质量和阅读体验 有兴趣吗

**Comment by chasewoo** [comment]
@SangKa 有的，非常乐意参加。

**Comment by SangKa** [comment]
@minowu 那十分欢迎
