### ISSUE TITLE
关于请求数据

### ISSUE THREAD

**Issue by yuhaiyang1** [SangKa/MobX-Docs-CN#5]
需不需要像redux一样用到中间件

**Comment by SangKa** [comment]
MobX 中没有 Redux 中的中间件概念
可以参考 [编写异步Actions](http://cn.mobx.js.org/best/actions.html)
希望对你有所帮助

**Comment by yuhaiyang1** [comment]
我这边有个疑惑，在关于使用react的时,在did生命周期里打印store里面有个属性citylist,然后接着打印store.citylist得到的undefined为啥但是我放在render里面就可以

**Comment by SangKa** [comment]
描述的太抽象了 不好定位问题
可以贴个在线demo之类的
