### ISSUE TITLE
mobx6文档

### ISSUE THREAD

**Issue by wangjq4214** [SangKa/MobX-Docs-CN#66]
mobx6的文档还会更新么

**Comment by iChenLei** [comment]
@wangjq4214 你好，我是Mobxjs Team Member，针对Mobx新版文档缺失的问题我们发起了官方文档翻译项目，项目仓库是https://github.com/mobxjs/zh.mobx.js.org ，翻译正在进行中，欢迎您参与贡献。:heart:

**Comment by wangjq4214** [comment]
@iChenLei okk
